#ifndef GDISPLAY_H
#define GDISPLAY_H

// Panel geometry macros kept for leftover Legacy coordinate references.
#define PANEL_NAMES_X 1
#define PANEL_NAMES_Y 37
#define PANEL_TABLES_X 60
#define PANEL_TABLES_Y 25
#define PANEL_INSTR_X 60
#define PANEL_INSTR_Y 18
#define PANEL_ORDER_X 60
#define PANEL_ORDER_Y 2
#define EXTENDEDVISIBLEORDERLIST 13

#define YES_NO_TEXT_X 2
#define YES_NO_TEXT_Y 40

#ifndef GDISPLAY_C
extern char debugtext[256];
#endif

#define FIRST_UI_COLOR 0x20

enum UI_COLORS {
	CPATTERN_BACKGROUND1 = FIRST_UI_COLOR,
	CPATTERN_FOREGROUND1,
	CPATTERN_BACKGROUND2,
	CPATTERN_FOREGROUND2,
	CPATTERN_HIGHLIGHT_BACKGROUND,
	CPATTERN_HIGHLIGHT_FOREGROUND,
	CPATTERN_NOTE_FOREGROUND,
	CPATTERN_COMMAND_FOREGROUND,
	CPATTERN_DIVIDER_LINE,
	CPATTERN_HIGHLIGHT_PLAYING_LINE_BACKGROUND,
	CPATTERN_HIGHLIGHT_PLAYING_LINE_FOREGROUND,
	CUNUSED_MUTED_BACKGROUND,
	CUNUSED_MUTED_FOREGROUND,
	CSELECT_TO_COPY_BACKGROUND,
	CSELECT_TO_COPY_FOREGROUND,
	CTABLE_BACKGROUND1,
	CTABLE_FOREGROUND1,
	CTABLE_BACKGROUND2,
	CTABLE_FOREGROUND2,
	CTABLE_UNUSED_BACKGROUND,
	CTABLE_UNUSED_FOREGROUND,
	CTABLE_SELECTED_INSTRUMENT_FOREGROUND,
	CTABLE_SELECTED_INSTRUMENT_BACKGROUND,
	CGENERAL_BACKGROUND,
	CTITLES_FOREGROUND,
	CINFO_FOREGROUND,
	CGENERAL_HIGHLIGHT,
	CTRANSPORT_BUTTON_BACKGROUND,
	CTRANSPORT_FOREGROUND,
	CTRANSPORT_ENABLED,
	CCOLOR_RED,
	CPATTERN_LOOP_MARKER_BACKGROUND,
	CPATTERN_LOOP_MARKER_FOREGROUND,
	CPATTERN_INSTRUMENT_FOREGROUND,
	CPATTERN_FIRST_BACKGROUND1,
	CPATTERN_FIRST_FOREGROUND1,
	CPATTERN_FIRST_BACKGROUND2,
	CPATTERN_FIRST_FOREGROUND2,
	CPATTERN_INDEX_HIGHLIGHT,
	CTRANSPORT_BACKGROUND2,
	TOPBAR_BACKGROUND,
	CTRANSPORT_BETWEEN_BUTTONS,
	CCOLOR_EXCLAMATION,
	CORDER_INST_BACKGROUND,
	CORDER_INST_FOREGROUND,
	CORDER_INST_TABLE_EDITING,
	CORDER_TRANS_REPEAT,
	TOPBAR_FOREGROUND,
	TOPBAR_FOREGROUND_OFF,
	CTRANSPORT_BUTTON_FOREGROUND
};

extern int UIUnderline;

#define PATTERN_X 0
#define PATTERN_Y 2 + 4 + 1 - 4 - 1

#define TRANSPORT_BAR_X 14
#define TRANSPORT_BAR_Y 33

#define CNORMAL 8
#define CMUTE 3
#define CEDIT 10
#define CPLAYING 12
#define CCOMMAND 7
#define CTITLE 15

#ifndef GDISPLAY_C
extern const char* notename[];
extern const char* notenameTableView[];
extern char timechar[];
#endif

void printmainscreen(GTOBJECT* gt);
void displayupdate(GTOBJECT* gt);
void resettime(GTOBJECT* gt);
void incrementtime(GTOBJECT* gt);
void setSongLengthTime(GTOBJECT* gt);
void setSIDTracker64KeyOnStyle();
int doDisplay(void* gt);

void updateDisplayWhenFollowingAndPlaying(GTOBJECT* gt);
void updateDisplayWhenFollowingAndPlaying_Expanded(GTOBJECT* gt);
void updateDisplayWhenFollowingAndPlaying_Compressed(GTOBJECT* gt);

#endif
