# Generate a C++ byte-array include from a list of resource files.
#
# Required variables:
#   OUT      - output path for the .inc
#   LISTFILE - text file with one absolute path per line

if(NOT OUT OR NOT LISTFILE)
  message(FATAL_ERROR "EmbedResources.cmake requires OUT and LISTFILE")
endif()

if(NOT EXISTS "${LISTFILE}")
  message(FATAL_ERROR "Embed list missing: ${LISTFILE}")
endif()

file(STRINGS "${LISTFILE}" FILES)

set(content "// Auto-generated by EmbedResources.cmake — do not edit.\n\n")

foreach(path IN LISTS FILES)
  if(path STREQUAL "")
    continue()
  endif()
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Embed resource missing: ${path}")
  endif()

  get_filename_component(fname "${path}" NAME)
  string(MAKE_C_IDENTIFIER "${fname}" sym)

  file(READ "${path}" hex HEX)
  string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1," hex "${hex}")

  string(APPEND content
    "static constexpr unsigned char k_bytes_${sym}[] = { ${hex} };\n"
    "static constexpr std::size_t k_size_${sym} = sizeof(k_bytes_${sym});\n\n")
endforeach()

file(WRITE "${OUT}" "${content}")
